---
duration: 0.5

sample_rate: None
clip_duration: None
target_stems: None

train_datasets:
    FDTD_2D:
        split: "train"
        skip: 5

test_datasets:
    FDTD_2D:
        split: "test"
        skip: 5
        select_num: 10

sampler: InfiniteSampler

data_transform: 
    name: Boundary2Field

model:
    name: BSRoformerMel
    y_dim:  # Leave blank if None
    c_dim:  1
    ct_dim:  # Leave blank if None
    ctf_dim: 2
    cx_dim:  # Leave blank if None
    cnn_dim:  # Leave blank if None

    in_channels: 1
    patch_size: [4, 4]
    n_layer: 12
    n_head: 12
    n_embd: 384

train:
    device: cuda
    num_workers: 64
    precision: "no"  # "no" (fp32) | "fp8" | "fp16" | bf16 
    loss: l1
    optimizer: AdamW
    lr: 1e-4
    warm_up_steps: 1000  # Leave blank if no warm up is used
    batch_size_per_device: 10
    test_every_n_steps: 2000
    save_every_n_steps: 20000
    training_steps: 300000
    resume_ckpt_path:  # Leave blank

valid_audios: # Leave blank
